apiVersion: v1
kind: Template
metadata:
  name: apache-zookeeper
  annotations:
    description: 1-pod ZooKeeper
    tags: messaging,zookeeper

parameters:
- name: VOLUME_CAPACITY
  description: Persistent volume capacity per pod, e.g. 512Mi, 2Gi
  required: true
  value: 216Mi
- name: NAME
  description: Name prefix for each object created
  required: true
  value: apache-zookeeper
- name: IMAGE
  description: Kafkanetes imagestream name
  required: true
  value: is-os/zk-is  
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: ${NAME}
  spec:
    replicas: 1
    selector:
      deploymentconfig: ${NAME}
    template:
      metadata:
        labels:
          deploymentconfig: ${NAME}
      spec:
        containers:
        - name: apache-zookeeper
          image: ${IMAGE}
          command:
          - bin/zookeeper-server-start.sh
          args:
          - config/zookeeper.properties
          volumeMounts:
          - mountPath: /tmp/zookeeper
            name: zookeeper
          ports:
          - containerPort: 2181
        volumes:
        - name: zookeeper
          persistentVolumeClaim:
            claimName: ${NAME}
- apiVersion: v1
  kind: Service
  metadata:
    name: ${NAME}
  spec:
    ports:
    - port: 2181
    selector:
      deploymentconfig: ${NAME}
